create schema if not exists hive.tpcds_parquet_100;
use hive.tpcds_parquet_100;
create table if not exists call_center with (format='parquet') as select * from tpcds.sf100.call_center;
create table if not exists catalog_page with (format='parquet') as select * from tpcds.sf100.catalog_page;
create table if not exists catalog_returns with (format='parquet') as select * from tpcds.sf100.catalog_returns;
create table if not exists catalog_sales with (format='parquet') as select * from tpcds.sf100.catalog_sales;
create table if not exists customer with (format='parquet') as select * from tpcds.sf100.customer;
create table if not exists customer_address with (format='parquet') as select * from tpcds.sf100.customer_address;
create table if not exists customer_demographics with (format='parquet') as select * from tpcds.sf100.customer_demographics;
create table if not exists date_dim with (format='parquet') as select * from tpcds.sf100.date_dim;
create table if not exists household_demographics with (format='parquet') as select * from tpcds.sf100.household_demographics;
create table if not exists income_band with (format='parquet') as select * from tpcds.sf100.income_band;
create table if not exists inventory with (format='parquet') as select * from tpcds.sf100.inventory;
create table if not exists item with (format='parquet') as select * from tpcds.sf100.item;
create table if not exists promotion with (format='parquet') as select * from tpcds.sf100.promotion;
create table if not exists reason with (format='parquet') as select * from tpcds.sf100.reason;
create table if not exists ship_mode with (format='parquet') as select * from tpcds.sf100.ship_mode;
create table if not exists store with (format='parquet') as select * from tpcds.sf100.store;
create table if not exists store_returns with (format='parquet') as select * from tpcds.sf100.store_returns;
create table if not exists store_sales with (format='parquet') as select * from tpcds.sf100.store_sales;
create table if not exists time_dim with (format='parquet') as select * from tpcds.sf100.time_dim;
create table if not exists warehouse with (format='parquet') as select * from tpcds.sf100.warehouse;
create table if not exists web_page with (format='parquet') as select * from tpcds.sf100.web_page;
create table if not exists web_returns with (format='parquet') as select * from tpcds.sf100.web_returns;
create table if not exists web_sales with (format='parquet') as select * from tpcds.sf100.web_sales;
create table if not exists web_site with (format='parquet') as select * from tpcds.sf100.web_site;
create schema if not exists hive.tpch_parquet_100;
use hive.tpch_parquet_100;
create table if not exists nation with (format='parquet') as select * from tpch.sf100.nation;
create table if not exists lineitem with (format='parquet') as select * from tpch.sf100.lineitem;
create table if not exists customer with (format='parquet') as select * from tpch.sf100.customer;
create table if not exists orders with (format='parquet') as select * from tpch.sf100.orders;
create table if not exists part with (format='parquet') as select * from tpch.sf100.part;
create table if not exists partsupp with (format='parquet') as select * from tpch.sf100.partsupp;
create table if not exists region with (format='parquet') as select * from tpch.sf100.region;
create table if not exists supplier with (format='parquet') as select * from tpch.sf100.supplier;
